# Generated by Django 5.0.3 on 2024-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='grampost',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
