# Generated by Django 5.0.3 on 2024-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_gramdislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.DeleteModel(
            name='GramAvatar',
        ),
    ]
