# Generated by Django 5.0.3 on 2024-03-21 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_profile_name_delete_gramavatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gramlike',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='gramlike',
            name='user_id',
        ),
        migrations.AddField(
            model_name='grampost',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grampost',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='media/avatar'),
        ),
        migrations.DeleteModel(
            name='GramDislike',
        ),
        migrations.DeleteModel(
            name='GramLike',
        ),
    ]
