# Generated by Django 5.0.3 on 2024-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='small_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
