# Generated by Django 5.0.3 on 2024-04-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_feedphotos_feed_id_feedpost_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedphotos',
            name='small_photo',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='photos',
        ),
        migrations.AddField(
            model_name='feedphotos',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='polls.feedpost'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
