# Generated by Django 5.0.3 on 2024-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_feedphotos_small_photo_remove_feedpost_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='grampost',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
