# Generated by Django 5.0.3 on 2024-04-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_feedpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedphotos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='polls.feedpost'),
        ),
    ]
